"""Add certificate_images table and support multi-image certificates

Revision ID: 132d98d0d497
Revises: d11faf2bb051
Create Date: 2026-08-04 14:51:41.159534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132d98d0d497'
down_revision: Union[str, Sequence[str], None] = 'd11faf2bb051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('page_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('certificates', 'public_id')
    op.drop_column('certificates', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('certificate_images')
    # ### end Alembic commands ###
