"""Add location to profile

Revision ID: 2572bf1ef12d
Revises: e7df408d7ddf
Create Date: 2026-08-07 21:00:23.955431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2572bf1ef12d'
down_revision: Union[str, Sequence[str], None] = 'e7df408d7ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'location')
    # ### end Alembic commands ###
