"""Add public_id to certificate

Revision ID: 4762b15896b7
Revises: ad897bab4c00
Create Date: 2026-07-31 21:07:42.911812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4762b15896b7'
down_revision: Union[str, Sequence[str], None] = 'ad897bab4c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'public_id')
    # ### end Alembic commands ###
