"""convert profile text fields to jsonb id/en

Revision ID: d11faf2bb051
Revises: 4762b15896b7
Create Date: 2026-08-03 10:17:49.332474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd11faf2bb051'
down_revision: Union[str, Sequence[str], None] = '4762b15896b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'tagline',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="CASE WHEN tagline IS NULL THEN NULL ELSE jsonb_build_object('id', tagline, 'en', '') END")
    op.alter_column('profile', 'about_heading',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="CASE WHEN about_heading IS NULL THEN NULL ELSE jsonb_build_object('id', about_heading, 'en', '') END")
    op.alter_column('profile', 'about_text',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="CASE WHEN about_text IS NULL THEN NULL ELSE jsonb_build_object('id', about_text, 'en', '') END")
    op.alter_column('profile_titles', 'text',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="CASE WHEN text IS NULL THEN NULL ELSE jsonb_build_object('id', text, 'en', '') END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_titles', 'text',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="text->>'id'")
    op.alter_column('profile', 'about_text',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using="about_text->>'id'")
    op.alter_column('profile', 'about_heading',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="about_heading->>'id'")
    op.alter_column('profile', 'tagline',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using="tagline->>'id'")
    # ### end Alembic commands ###
